<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbOfEvents(){
        return $this->createQueryBuilder('e')
            ->select('COUNT(e)')
            ->from('AppBundle:Event', 'event')
            ->getQuery()
            ->getResult();
    }
}
